admins:
  - 80351110224678912
  - 108598213681922048

whitelist_roles:
  - 41771983423143936
  - 232930153943138324
  - 180036462832648192
  - 203287359125585920
  - 231560987508080650

filter_invites: true

filter_invites_whitelist:
  - discord-developers
  - discord-api
  - discord-testers

filter_nicknames: true

filter_nicknames_words:
  slut: ''

filter_nicknames_prefixes:
  - '!'

filter_usernames: true
filter_usernames_startup: true

filter_usernames_words:
  slut: ''

mention_tracker: true
mention_threshold: 10
mention_reset_time: 60
mention_action: none

spam_detection: true
spam_threshold: 15
spam_reset_time: 30
spam_action: none
